<div id="bookings-timeline" class="position-relative">
    <div class="position-absolute w-100 h-100 d-flex justify-content-center align-items-center" id="bookings-timeline-loading" style="background: rgba(255, 255, 255, 0.8); z-index: 1000;" hidden>
        <div class="spinner-border text-primary" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
</div>
