#!/usr/bin/perl

# Copyright 2022 LMSCloud GmbH
#
# This file is part of Koha.
#
# Koha is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Koha is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Koha; if not, see <http://www.gnu.org/licenses>.

=head1 DESCRIPTION

Return catalogue data that is needed to support coverflows in Koha.

=cut

use Modern::Perl;

use CGI qw ( -utf8 );

use C4::Context;
use C4::Auth;
use C4::Output;
use C4::CoverFlowData qw(GetCoverFlowDataByBiblionumber);


my @bibids;

my $cgi = CGI->new;
if ( $cgi && $cgi->param('bibid') ) {
    foreach my $splitId( split /(\s+|,)/, $cgi->param('bibid')  ) {
        if ( $splitId =~ /^\d+$/ ) {
            push @bibids, $splitId;
        }
    }
}

my ( $template, $borrowernumber, $cookie ) = get_template_and_user(
    {
        template_name   => "svc/coverflowbybib.tt",
        query           => $cgi,
        type            => "opac",
        authnotrequired => ( C4::Context->preference("OpacPublic") ? 1 : 0 ),
    }
);

my $coverdata = GetCoverFlowDataByBiblionumber(@bibids);
$template->param(
    count => (exists($coverdata->{count}) ? $coverdata->{count} : 0),
    items => (exists($coverdata->{items}) ? $coverdata->{items} : ())
);

output_with_http_headers $cgi, $cookie, $template->output, 'json';
