#!/usr/bin/perl

# Copyright 2022 LMSCloud GmbH
#
# This file is part of Koha.
#
# Koha is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Koha is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Koha; if not, see <http://www.gnu.org/licenses>.

=head1 DESCRIPTION

Return catalogue data that is needed to support coverflows in Koha.

=cut

use Modern::Perl;
use utf8;

use CGI qw ( -utf8 );

use C4::Context;
use C4::Auth;
use C4::Output;
use C4::External::BibtipRecommendations;

my $cgi = CGI->new;

my ( $template, $borrowernumber, $cookie ) = get_template_and_user(
    {   template_name   => "svc/user-recommendations.tt",
        query           => $cgi,
        type            => "opac",
        authnotrequired => ( C4::Context->preference("OpacPublic") ? 1 : 0 ),
    }
);

# get cover flow data used for the recommendations
if ( C4::Context->preference("BibtipPatronSpecificRecommendations") ) {
    my $borrowernumber = C4::Context->userenv->{'number'};

    if ( defined($borrowernumber) ) {
        my $bibtip    = C4::External::BibtipRecommendations->new;
        my $count     = $cgi->param('count');
        my $coverdata = $bibtip->getPatronSpecificRecommendations( $borrowernumber, $count );

        my $is_hashref = ref($coverdata) eq 'HASH';
        $template->param(
            count => $is_hashref ? ( $coverdata->{count} // 0 )  : 0,
            items => $is_hashref ? ( $coverdata->{items} // () ) : ()
        );
    }
}

output_with_http_headers $cgi, $cookie, $template->output, 'json';
