type: object
properties:
  authorised_value_id:
    description: The internal id for this authorised value
  category_name:
    description: The category of this authorised value
  value:
    description: The code for this authorised value
  description:
    description: The staff interface description for this authorised value
  opac_description:
    type:
      - string
      - 'null'
    description: The public interface description of this authorised value, if set
  image_url:
    type:
      - string
      - 'null'
    description: The url of the image associated with this authorised value, if any
