<fieldset class="action filters d-flex gap-2" style="cursor: pointer;">
    <a id="bookings_expired_filter" class="bookings-table-filter" data-filter="expired"><i class="fa fa-bars"></i> Include expired</a>
    <a id="bookings_cancelled_filter" class="bookings-table-filter" data-filter="cancelled"><i class="fa fa-bars"></i> Include cancelled</a>
    <a id="bookings_completed_filter" class="bookings-table-filter" data-filter="completed"><i class="fa fa-bars"></i> Include completed</a>
</fieldset> 