<!-- ill-list-table-strings.inc -->
<script>
    var ill_manage = _("Manage request");
    var ill_manage_select_backend_first = _("Select a backend first");
    var ill_all_statuses = _("All statuses");

    var ill_columns = {
        biblio_id: _("Bibliographic record ID"),
        updated: _("Updated on"),
        type: _("Type")
    };

    var ill_medium = {
        Book: _("Book"),
        Article: _("Article"),
        Journal: _("Journal"),
        Other: _("Other")
    };

    var ill_backend = {
        ILLALV: _("ALV"),
        ILLSLNPKoha: _("SLNP-passive"),
        ILLZKSHA: _("RLV-active"),
        ILLZKSHP: _("RLV-passive"),
        PFL: _("PFL")
    };
</script>
<!-- / ill-list-table-strings.inc -->
