<!-- ill-list-table-strings.inc -->
<script>
    var ill_borrower_details = _("View borrower details");
    var ill_biblio_details = _("View biblio details");
    var ill_manage = _("Manage request");

    var ill_statuses = {
        new: _("New request"),
        req: _("Requested"),
        genreq: _("Requested from partners"),
        rev: _("Reverted"),
        que: _("Queued request"),
        canc: _("Cancellation requested"),
        comp: _("Completed"),
        del: _("Delete request")
    };

    var ill_columns = {
        biblio_id: _("Bibliographic record ID"),
        updated: _("Updated on"),
        type: _("Type")
    };

    var ill_medium = {
        Book: _("Book"),
        Article: _("Article"),
        Journal: _("Journal"),
        Other: _("Other")
    };

    var ill_backend = {
        ILLALV: _("ALV"),
        ILLSLNPKoha: _("SLNP-passive"),
        ILLZKSHA: _("RLV-active"),
        ILLZKSHP: _("RLV-passive"),
        PFL: _("PFL")
    };
</script>
<!-- / ill-list-table-strings.inc -->
